### ISSUE TITLE
Convert datetime strings to datetime objects

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/shellhub-python#3]
Strings returned by the ShellHub API need to be converted to datetime objects

**Comment by swapnil-veer** [comment]
Hello Jules,
Can you throw more light on the issue

**Comment by Seluj78** [comment]
Yes of course !

I would like the datetime strings stored in `ShellHubDevice` to be actual python datetime objects and not just strings

I am talking about these ones:
https://github.com/Seluj78/shellhub-python/blob/521a6f204523f22f633b48785f75570292957037/shellhub/models/device.py#L62
https://github.com/Seluj78/shellhub-python/blob/521a6f204523f22f633b48785f75570292957037/shellhub/models/device.py#L66
https://github.com/Seluj78/shellhub-python/blob/521a6f204523f22f633b48785f75570292957037/shellhub/models/device.py#L67

All that is needed for this issue is to convert the strings into a nice datetime object and add tests for it :)
